package numberpuzzle;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
/**
 *
 * @author Shalu
 */
public class puzzle extends javax.swing.JFrame {
    String name;
    /**
     * Creates new form puzzle
     */
    public puzzle(String name) {
        this.setResizable(false);
        initComponents();
        this.setDisable();
        this.name = name;       //for disabling all the buttons (user defined method)
    }
    public class Timer extends Thread{
        public void run(){
            int sec = 0, min = 0;
            while (true) {
                if (sec == 59) {
                    sec = 0;
                    if (min < 9) {
                        startTimerLabel.setText("0" + String.valueOf(++min) + ":0" + String.valueOf(sec));
                    } 
                    else {
                        startTimerLabel.setText(String.valueOf(++min) + ":0" + String.valueOf(sec));
                    }

                } 
                else {
                    if (sec >= 9 && min <= 9) {
                        startTimerLabel.setText("0" + String.valueOf(min) + ":" + String.valueOf(++sec));
                    }
                    if (sec >= 9 && min >= 10) {
                        startTimerLabel.setText(String.valueOf(min) + ":" + String.valueOf(++sec));
                    }
                    if (sec < 9 && min >= 10) {
                        startTimerLabel.setText(String.valueOf(min) + ":0" + String.valueOf(++sec));
                    }
                    if (sec < 9 && min <= 9) {
                        startTimerLabel.setText("0" + String.valueOf(min) + ":0" + String.valueOf(++sec));
                    }
                }
                try {
                    sleep(1000);
                } 
                catch (InterruptedException e) {
                }
            } 
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        startTimerLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        b4 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        bReset = new javax.swing.JButton();
        b9 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 204));
        setForeground(new java.awt.Color(255, 51, 51));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(0, 0, 255));

        startTimerLabel.setBackground(new java.awt.Color(0, 0, 0));
        startTimerLabel.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        startTimerLabel.setForeground(new java.awt.Color(0, 255, 0));
        startTimerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        startTimerLabel.setText("Start");
        startTimerLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StartLbelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(startTimerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startTimerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(96, 19, 34));

        b4.setFont(new java.awt.Font("Arial Narrow", 3, 48)); // NOI18N
        b4.setForeground(new java.awt.Color(0, 0, 255));
        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b1.setFont(new java.awt.Font("Arial Narrow", 3, 48)); // NOI18N
        b1.setForeground(new java.awt.Color(255, 0, 255));
        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b5.setFont(new java.awt.Font("Arial Narrow", 3, 48)); // NOI18N
        b5.setForeground(new java.awt.Color(255, 255, 51));
        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.setFont(new java.awt.Font("Arial Narrow", 3, 48)); // NOI18N
        b6.setForeground(new java.awt.Color(0, 255, 255));
        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b7.setFont(new java.awt.Font("Arial Narrow", 3, 48)); // NOI18N
        b7.setForeground(new java.awt.Color(255, 0, 0));
        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b2.setFont(new java.awt.Font("Arial Narrow", 3, 48)); // NOI18N
        b2.setForeground(new java.awt.Color(255, 51, 51));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setFont(new java.awt.Font("Arial Narrow", 3, 48)); // NOI18N
        b3.setForeground(new java.awt.Color(0, 255, 51));
        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b8.setFont(new java.awt.Font("Arial Narrow", 3, 48)); // NOI18N
        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        bReset.setBackground(new java.awt.Color(255, 51, 51));
        bReset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bReset.setText(" RESET");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });

        b9.setFont(new java.awt.Font("Arial Narrow", 3, 48)); // NOI18N
        b9.setForeground(new java.awt.Color(255, 255, 0));
        b9.setText("2");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(bReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bReset, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        String s= b5.getText();
        if(b2.getText().equals("")){
            b2.setText(s); 
            b5.setText("");
        }
        else if(b4.getText().equals("")){
            b4.setText(s);
            b5.setText("");
        }
        else if(b6.getText().equals("")){
            b6.setText(s);
            b5.setText("");
        }
        else if(b8.getText().equals("")){
            b8.setText(s);
            b5.setText("");}
        this.winCheck();
    }//GEN-LAST:event_b5ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        String s= b8.getText();
        if(b9.getText().equals("")){
            b9.setText(s);
            b8.setText("");
        }
        else if(b5.getText().equals("")){
            b5.setText(s);
            b8.setText("");
        }
        else if(b7.getText().equals("")){
            b7.setText(s);
            b8.setText("");
        }
        this.winCheck();
    }//GEN-LAST:event_b8ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        String s= b1.getText();
        if(b2.getText().equals("")){
            b2.setText(s);
            b1.setText("");
        }
        else if(b4.getText().equals("")){
            b4.setText(s);
            b1.setText("");
        }
        this.winCheck();
    }//GEN-LAST:event_b1ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        String s= b3.getText();
        if(b2.getText().equals("")){ 
            b2.setText(s); 
            b3.setText("");
        }
        else if(b6.getText().equals("")){
            b6.setText(s);
            b3.setText("");
        }
        this.winCheck();
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        String s= b4.getText();
        if(b1.getText().equals("")){
            b1.setText(s);
            b4.setText("");
        }
        else if(b7.getText().equals("")){
            b7.setText(s);
            b4.setText("");
        }
        else if(b5.getText().equals("")){ 
            b5.setText(s);
            b4.setText("");
        }
        this.winCheck();
    }//GEN-LAST:event_b4ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        String s= b2.getText();
        if(b1.getText().equals("")){
            b1.setText(s);
            b2.setText("");
        }
        else if(b3.getText().equals("")){
            b3.setText(s); 
            b2.setText("");
        }
        else if(b5.getText().equals("")){
            b5.setText(s); 
            b2.setText("");
        }
        this.winCheck();
    }//GEN-LAST:event_b2ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        String s= b6.getText();
        if(b3.getText().equals("")){ 
            b3.setText(s);
            b6.setText("");
        }
        else if(b9.getText().equals("")){
            b9.setText(s);
            b6.setText("");
        }
        else if(b5.getText().equals("")){
            b5.setText(s);
            b6.setText("");
        }
        this.winCheck();
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        String s= b7.getText();
        if(b4.getText().equals("")){
            b4.setText(s);
            b7.setText("");
        }
        else if(b8.getText().equals("")){
            b8.setText(s);
            b7.setText("");
        }
        this.winCheck();
    }//GEN-LAST:event_b7ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        String s= b9.getText();
        if(b6.getText().equals("")){
            b6.setText(s);
            b9.setText("");
        } 
        else if(b8.getText().equals("")){
            b8.setText(s); 
            b9.setText("");
        }
        this.winCheck();
    }//GEN-LAST:event_b9ActionPerformed

    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        this.resetMethod();
    }//GEN-LAST:event_bResetActionPerformed

    private void StartLbelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartLbelMouseClicked
        this.setEnable();
        boolean Start = false;
        if(startTimerLabel.getText().equals("Start")){
            Timer obj=new Timer();
            obj.start();
        }

        
        
        
        
        
    }//GEN-LAST:event_StartLbelMouseClicked
    private void winCheck(){
        if(b1.getText().equals("1") && b2.getText().equals("2") && 
                b3.getText().equals("3") && b4.getText().equals("4") &&
                b5.getText().equals("5") && b6.getText().equals("6") && 
                b7.getText().equals("7") && b8.getText().equals("8") &&
                b9.getText().equals("")
           ){   
            //JOptionPane.showMessageDialog(puzzle.this,"!!!you won!!!");  
            this.setVisible(false);
            String time=startTimerLabel.getText();
            Final FinalObj = new Final(this.name,time);
            FinalObj.setVisible(true);
            FinalObj.setLabelAndTextValues();
            
        }
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(puzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(puzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(puzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(puzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bReset;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel startTimerLabel;
    // End of variables declaration//GEN-END:variables

public void resetMethod(){
    ArrayList<String> mylist = new ArrayList<String>();
    mylist.add("1");
    mylist.add("2");
    mylist.add("3");
    mylist.add("4");
    mylist.add("5");
    mylist.add("6");
    mylist.add("7");
    mylist.add("8");
    mylist.add("");
    Collections.shuffle(mylist);
    
     

    
b1.setText(mylist.get(0));
b2.setText(mylist.get(1));
b3.setText(mylist.get(2));
b4.setText(mylist.get(3));
b5.setText(mylist.get(4));
b6.setText(mylist.get(5));
b7.setText(mylist.get(6));
b8.setText(mylist.get(7));
b9.setText(mylist.get(8));
}

public void setDisable(){
    b1.setEnabled(false);
    b2.setEnabled(false);
    b3.setEnabled(false);
    b4.setEnabled(false);
    b5.setEnabled(false);
    b6.setEnabled(false);    
    b7.setEnabled(false);
    b8.setEnabled(false);
    b9.setEnabled(false);  
    bReset.setEnabled(false);  
}
public void setEnable(){
    b1.setEnabled(true);
    b2.setEnabled(true);
    b3.setEnabled(true);
    b4.setEnabled(true);
    b5.setEnabled(true);
    b6.setEnabled(true);
    b7.setEnabled(true);
    b7.setEnabled(true);
    b8.setEnabled(true);
    b9.setEnabled(true);
    bReset.setEnabled(true);
    
}
}

    
    
    

        
        






